// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: vacancy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vacancy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title        string      `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug         string      `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description  string      `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Salary       string      `protobuf:"bytes,5,opt,name=salary,proto3" json:"salary,omitempty"`
	IsActive     bool        `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsDistribute bool        `protobuf:"varint,7,opt,name=is_distribute,json=isDistribute,proto3" json:"is_distribute,omitempty"`
	Order        int64       `protobuf:"varint,8,opt,name=order,proto3" json:"order,omitempty"`
	Cities       []*City     `protobuf:"bytes,9,rep,name=cities,proto3" json:"cities,omitempty"`
	Categories   []*Category `protobuf:"bytes,10,rep,name=categories,proto3" json:"categories,omitempty"`
	CreatedAt    string      `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt    string      `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Vacancy) Reset() {
	*x = Vacancy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vacancy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vacancy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacancy) ProtoMessage() {}

func (x *Vacancy) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacancy.ProtoReflect.Descriptor instead.
func (*Vacancy) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{0}
}

func (x *Vacancy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vacancy) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Vacancy) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Vacancy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Vacancy) GetSalary() string {
	if x != nil {
		return x.Salary
	}
	return ""
}

func (x *Vacancy) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Vacancy) GetIsDistribute() bool {
	if x != nil {
		return x.IsDistribute
	}
	return false
}

func (x *Vacancy) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Vacancy) GetCities() []*City {
	if x != nil {
		return x.Cities
	}
	return nil
}

func (x *Vacancy) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Vacancy) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Vacancy) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ReadVacancyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadVacancyRequest) Reset() {
	*x = ReadVacancyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vacancy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadVacancyRequest) ProtoMessage() {}

func (x *ReadVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadVacancyRequest.ProtoReflect.Descriptor instead.
func (*ReadVacancyRequest) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{1}
}

func (x *ReadVacancyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadVacancyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vacancy *Vacancy `protobuf:"bytes,1,opt,name=vacancy,proto3" json:"vacancy,omitempty"`
}

func (x *ReadVacancyResponse) Reset() {
	*x = ReadVacancyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vacancy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadVacancyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadVacancyResponse) ProtoMessage() {}

func (x *ReadVacancyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadVacancyResponse.ProtoReflect.Descriptor instead.
func (*ReadVacancyResponse) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{2}
}

func (x *ReadVacancyResponse) GetVacancy() *Vacancy {
	if x != nil {
		return x.Vacancy
	}
	return nil
}

type ListVacancyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListVacancyRequest) Reset() {
	*x = ListVacancyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vacancy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVacancyRequest) ProtoMessage() {}

func (x *ListVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVacancyRequest.ProtoReflect.Descriptor instead.
func (*ListVacancyRequest) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{3}
}

type ListVacancyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vacancies []*Vacancy `protobuf:"bytes,1,rep,name=vacancies,proto3" json:"vacancies,omitempty"`
}

func (x *ListVacancyResponse) Reset() {
	*x = ListVacancyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vacancy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVacancyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVacancyResponse) ProtoMessage() {}

func (x *ListVacancyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVacancyResponse.ProtoReflect.Descriptor instead.
func (*ListVacancyResponse) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{4}
}

func (x *ListVacancyResponse) GetVacancies() []*Vacancy {
	if x != nil {
		return x.Vacancies
	}
	return nil
}

type CreateVacancyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title        string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description  string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Salary       string   `protobuf:"bytes,3,opt,name=salary,proto3" json:"salary,omitempty"`
	IsActive     bool     `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsDistribute bool     `protobuf:"varint,5,opt,name=is_distribute,json=isDistribute,proto3" json:"is_distribute,omitempty"`
	Order        int64    `protobuf:"varint,6,opt,name=order,proto3" json:"order,omitempty"`
	Cities       []string `protobuf:"bytes,7,rep,name=cities,proto3" json:"cities,omitempty"`
	Categories   []string `protobuf:"bytes,8,rep,name=categories,proto3" json:"categories,omitempty"`
}

func (x *CreateVacancyReq) Reset() {
	*x = CreateVacancyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vacancy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVacancyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVacancyReq) ProtoMessage() {}

func (x *CreateVacancyReq) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVacancyReq.ProtoReflect.Descriptor instead.
func (*CreateVacancyReq) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{5}
}

func (x *CreateVacancyReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateVacancyReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateVacancyReq) GetSalary() string {
	if x != nil {
		return x.Salary
	}
	return ""
}

func (x *CreateVacancyReq) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CreateVacancyReq) GetIsDistribute() bool {
	if x != nil {
		return x.IsDistribute
	}
	return false
}

func (x *CreateVacancyReq) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *CreateVacancyReq) GetCities() []string {
	if x != nil {
		return x.Cities
	}
	return nil
}

func (x *CreateVacancyReq) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CreateVacancyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateVacancyResponse) Reset() {
	*x = CreateVacancyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vacancy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVacancyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVacancyResponse) ProtoMessage() {}

func (x *CreateVacancyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVacancyResponse.ProtoReflect.Descriptor instead.
func (*CreateVacancyResponse) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{6}
}

func (x *CreateVacancyResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateVacancyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateVacancyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title        string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description  string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Salary       string   `protobuf:"bytes,4,opt,name=salary,proto3" json:"salary,omitempty"`
	IsActive     bool     `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsDistribute bool     `protobuf:"varint,6,opt,name=is_distribute,json=isDistribute,proto3" json:"is_distribute,omitempty"`
	Order        int64    `protobuf:"varint,7,opt,name=order,proto3" json:"order,omitempty"`
	Cities       []string `protobuf:"bytes,8,rep,name=cities,proto3" json:"cities,omitempty"`
	Categories   []string `protobuf:"bytes,9,rep,name=categories,proto3" json:"categories,omitempty"`
}

func (x *UpdateVacancyReq) Reset() {
	*x = UpdateVacancyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vacancy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVacancyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVacancyReq) ProtoMessage() {}

func (x *UpdateVacancyReq) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVacancyReq.ProtoReflect.Descriptor instead.
func (*UpdateVacancyReq) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateVacancyReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateVacancyReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateVacancyReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateVacancyReq) GetSalary() string {
	if x != nil {
		return x.Salary
	}
	return ""
}

func (x *UpdateVacancyReq) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UpdateVacancyReq) GetIsDistribute() bool {
	if x != nil {
		return x.IsDistribute
	}
	return false
}

func (x *UpdateVacancyReq) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *UpdateVacancyReq) GetCities() []string {
	if x != nil {
		return x.Cities
	}
	return nil
}

func (x *UpdateVacancyReq) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type UpdateVacancyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateVacancyResponse) Reset() {
	*x = UpdateVacancyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vacancy_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVacancyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVacancyResponse) ProtoMessage() {}

func (x *UpdateVacancyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVacancyResponse.ProtoReflect.Descriptor instead.
func (*UpdateVacancyResponse) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateVacancyResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateVacancyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteVacancyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteVacancyRequest) Reset() {
	*x = DeleteVacancyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vacancy_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVacancyRequest) ProtoMessage() {}

func (x *DeleteVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVacancyRequest.ProtoReflect.Descriptor instead.
func (*DeleteVacancyRequest) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteVacancyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteVacancyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteVacancyResponse) Reset() {
	*x = DeleteVacancyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vacancy_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVacancyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVacancyResponse) ProtoMessage() {}

func (x *DeleteVacancyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVacancyResponse.ProtoReflect.Descriptor instead.
func (*DeleteVacancyResponse) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteVacancyResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeleteVacancyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_vacancy_proto protoreflect.FileDescriptor

var file_vacancy_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x1a, 0x0e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xe3, 0x02, 0x0a, 0x07, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x73, 0x6c, 0x75, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x61, 0x6c, 0x61, 0x72,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x12,
	0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x69, 0x73, 0x5f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x06, 0x63, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x69, 0x74,
	0x79, 0x52, 0x06, 0x63, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x0a, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x0a, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x24, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x56, 0x61, 0x63,
	0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3c, 0x0a, 0x13, 0x52,
	0x65, 0x61, 0x64, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x25, 0x0a, 0x07, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79,
	0x52, 0x07, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x4c, 0x69, 0x73,
	0x74, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x40, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x09, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63,
	0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x56,
	0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x09, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x69, 0x65,
	0x73, 0x22, 0xf2, 0x01, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x61, 0x63, 0x61,
	0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x73, 0x5f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x44, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x63, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x22, 0x49, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x82, 0x02, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x61, 0x63, 0x61,
	0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x73, 0x5f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x44, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x63, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x22, 0x49, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x26, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e,
	0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x49, 0x0a, 0x15, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x32, 0xdc, 0x02, 0x0a, 0x0e, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x19,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x52, 0x65, 0x61,
	0x64, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0d, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71,
	0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x61, 0x63, 0x61,
	0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0d, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x12, 0x18, 0x2e, 0x70,
	0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x40, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x69,
	0x65, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x63, 0x61,
	0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x73, 0x61, 0x6e, 0x7a, 0x68, 0x61, 0x72, 0x61, 0x6e, 0x61, 0x72, 0x62, 0x61, 0x79,
	0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x5f, 0x67, 0x52, 0x50, 0x43, 0x5f, 0x6d, 0x6f, 0x6e,
	0x67, 0x6f, 0x44, 0x42, 0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vacancy_proto_rawDescOnce sync.Once
	file_vacancy_proto_rawDescData = file_vacancy_proto_rawDesc
)

func file_vacancy_proto_rawDescGZIP() []byte {
	file_vacancy_proto_rawDescOnce.Do(func() {
		file_vacancy_proto_rawDescData = protoimpl.X.CompressGZIP(file_vacancy_proto_rawDescData)
	})
	return file_vacancy_proto_rawDescData
}

var file_vacancy_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_vacancy_proto_goTypes = []interface{}{
	(*Vacancy)(nil),               // 0: pb.Vacancy
	(*ReadVacancyRequest)(nil),    // 1: pb.ReadVacancyRequest
	(*ReadVacancyResponse)(nil),   // 2: pb.ReadVacancyResponse
	(*ListVacancyRequest)(nil),    // 3: pb.ListVacancyRequest
	(*ListVacancyResponse)(nil),   // 4: pb.ListVacancyResponse
	(*CreateVacancyReq)(nil),      // 5: pb.CreateVacancyReq
	(*CreateVacancyResponse)(nil), // 6: pb.CreateVacancyResponse
	(*UpdateVacancyReq)(nil),      // 7: pb.UpdateVacancyReq
	(*UpdateVacancyResponse)(nil), // 8: pb.UpdateVacancyResponse
	(*DeleteVacancyRequest)(nil),  // 9: pb.DeleteVacancyRequest
	(*DeleteVacancyResponse)(nil), // 10: pb.DeleteVacancyResponse
	(*City)(nil),                  // 11: pb.City
	(*Category)(nil),              // 12: pb.Category
}
var file_vacancy_proto_depIdxs = []int32{
	11, // 0: pb.Vacancy.cities:type_name -> pb.City
	12, // 1: pb.Vacancy.categories:type_name -> pb.Category
	0,  // 2: pb.ReadVacancyResponse.vacancy:type_name -> pb.Vacancy
	0,  // 3: pb.ListVacancyResponse.vacancies:type_name -> pb.Vacancy
	5,  // 4: pb.VacancyService.CreateVacancy:input_type -> pb.CreateVacancyReq
	1,  // 5: pb.VacancyService.ReadVacancy:input_type -> pb.ReadVacancyRequest
	7,  // 6: pb.VacancyService.UpdateVacancy:input_type -> pb.UpdateVacancyReq
	9,  // 7: pb.VacancyService.DeleteVacancy:input_type -> pb.DeleteVacancyRequest
	3,  // 8: pb.VacancyService.ListVacancies:input_type -> pb.ListVacancyRequest
	6,  // 9: pb.VacancyService.CreateVacancy:output_type -> pb.CreateVacancyResponse
	2,  // 10: pb.VacancyService.ReadVacancy:output_type -> pb.ReadVacancyResponse
	8,  // 11: pb.VacancyService.UpdateVacancy:output_type -> pb.UpdateVacancyResponse
	10, // 12: pb.VacancyService.DeleteVacancy:output_type -> pb.DeleteVacancyResponse
	4,  // 13: pb.VacancyService.ListVacancies:output_type -> pb.ListVacancyResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_vacancy_proto_init() }
func file_vacancy_proto_init() {
	if File_vacancy_proto != nil {
		return
	}
	file_category_proto_init()
	file_city_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_vacancy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vacancy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vacancy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadVacancyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vacancy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadVacancyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vacancy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVacancyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vacancy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVacancyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vacancy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVacancyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vacancy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVacancyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vacancy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVacancyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vacancy_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVacancyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vacancy_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteVacancyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vacancy_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteVacancyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vacancy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vacancy_proto_goTypes,
		DependencyIndexes: file_vacancy_proto_depIdxs,
		MessageInfos:      file_vacancy_proto_msgTypes,
	}.Build()
	File_vacancy_proto = out.File
	file_vacancy_proto_rawDesc = nil
	file_vacancy_proto_goTypes = nil
	file_vacancy_proto_depIdxs = nil
}
